// mockBooksData.js - Sample data for testing the MyLibrary component

const mockBooks = [
  {
    id: "1",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description: "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it. Set in the mid-1930s, this classic tale of injustice has resonated with readers for decades.",
    category: "Fiction",
    pages: 281,
    memories: "Read this during summer vacation at the lake house. I remember being deeply moved by Atticus Finch's character.",
    comment: "A powerful exploration of racial injustice and moral growth through a child's perspective.",
    rating: 5,
    googleId: "PGR2AwAAQBAJ",
    coverImage: "https://books.google.com/books/content?id=PGR2AwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    startDate: "2023-06-12T00:00:00.000Z",
    endDate: "2023-06-28T00:00:00.000Z"
  },
  {
    id: "2",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    description: "From a renowned historian comes a groundbreaking narrative of humanity's creation and evolution that explores the ways in which biology and history have defined us.",
    category: "Non-Fiction",
    pages: 443,
    memories: "This book completely changed how I view human history and our place in the world.",
    comment: "Fascinating perspective on how Homo sapiens came to dominate the planet.",
    rating: 4,
    googleId: "1EiJAwAAQBAJ",
    coverImage: "https://books.google.com/books/content?id=1EiJAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    startDate: "2023-08-05T00:00:00.000Z",
    endDate: "2023-09-10T00:00:00.000Z"
  },
  {
    id: "3",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    description: "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep.",
    category: "Fantasy",
    pages: 310,
    memories: "First read this as a child, and it sparked my lifelong love of fantasy literature.",
    comment: "A perfect introduction to Middle-earth and Tolkien's magnificent storytelling.",
    rating: 5,
    googleId: "pD6arNyKyi8C",
    coverImage: "https://books.google.com/books/content?id=pD6arNyKyi8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    startDate: "2022-12-15T00:00:00.000Z",
    endDate: "2023-01-05T00:00:00.000Z"
  },
  {
    id: "4",
    title: "Educated",
    author: "Tara Westover",
    description: "An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.",
    category: "Memoir",
    pages: 334,
    memories: "Read this during a difficult time in my life and found it incredibly inspiring.",
    comment: "A remarkable testament to the power of education and self-invention.",
    rating: 5,
    googleId: "XU0oAQAAQBAJ",
    coverImage: "https://books.google.com/books/content?id=XU0oAQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "2023-03-20T00:00:00.000Z"
  },
  {
    id: "5",
    title: "Atomic Habits",
    author: "James Clear",
    description: "A revolutionary guide to building good habits and breaking bad ones. Learn how tiny changes can yield remarkable results over time.",
    category: "Self-Help",
    pages: 320,
    memories: "Started applying the 1% better concept to my daily routine after reading this.",
    comment: "Practical advice that's actually changed my approach to habit formation.",
    rating: 4,
    googleId: "fFCjDwAAQBAJ",
    coverImage: "https://books.google.com/books/content?id=fFCjDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    startDate: "2024-01-02T00:00:00.000Z",
    endDate: "2024-01-15T00:00:00.000Z"
  },
  {
    id: "6",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description: "Set in the Jazz Age on Long Island, the novel depicts first-person narrator Nick Carraway's interactions with mysterious millionaire Jay Gatsby and Gatsby's obsession to reunite with his former lover, Daisy Buchanan.",
    category: "Fiction",
    pages: 180,
    memories: "Read this on a rainy weekend in April. The ending stayed with me for weeks.",
    comment: "Beautiful prose exploring the American Dream and its discontents.",
    rating: 4,
    googleId: "iXn5U2IzVH0C",
    coverImage: "https://books.google.com/books/content?id=iXn5U2IzVH0C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    startDate: "2023-04-15T00:00:00.000Z",
    endDate: "2023-04-17T00:00:00.000Z"
  },
  {
    id: "7",
    title: "Dune",
    author: "Frank Herbert",
    description: "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the "spice" melange.",
    category: "Science Fiction",
    pages: 688,
    memories: "Borrowed this from a friend who insisted it would change how I think about science fiction.",
    comment: "An epic blend of adventure, mysticism, politics, and ecology.",
    rating: 5,
    googleId: "B1hSG45JCX4C",
    coverImage: "https://books.google.com/books/content?id=B1hSG45JCX4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    startDate: "2023-10-10T00:00:00.000Z",
    endDate: "2023-11-15T00:00:00.000Z"
  },
  {
    id: "8",
    title: "The Four Agreements",
    author: "Don Miguel Ruiz",
    description: "In The Four Agreements, don Miguel Ruiz reveals the source of self-limiting beliefs that rob us of joy and create needless suffering.",
    category: "Self-Help",
    pages: 160,
    memories: "A friend recommended this during a difficult time. It helped me gain perspective.",
    comment: "Simple principles with profound implications for personal freedom.",
    rating: 3,
    googleId: "B6iqDwAAQBAJ",
    coverImage: "https://books.google.com/books/content?id=B6iqDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    startDate: "2024-02-05T00:00:00.000Z",
    endDate: null
  },
  {
    id: "9",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    description: "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London's most desirable areas. One evening her husband Gabriel returns home late from a fashion shoot, and Alicia shoots him five times in the face, and then never speaks another word.",
    category: "Thriller",
    pages: 325,
    memories: "Read this on a long flight and couldn't put it down.",
    comment: "The twist at the end completely blindsided me. Excellent psychological thriller.",
    rating: 4,
    googleId: "FzVjBgAAQBAJ",
    coverImage: "https://books.google.com/books/content?id=FzVjBgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    startDate: "2023-07-12T00:00:00.000Z",
    endDate: "2023-07-14T00:00:00.000Z"
  },
  {
    id: "10",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: "Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work 'her own darling child' and its vivacious heroine, Elizabeth Bennet, 'as delightful a creature as ever appeared in print.'",
    category: "Classic",
    pages: 432,
    memories: "My first Austen novel. I remember being surprised by how funny and relevant it still feels.",
    comment: "Witty, romantic, and a brilliant commentary on social expectations.",
    rating: 5,
    googleId: "x1uuDwAAQBAJ",
    coverImage: "https://books.google.com/books/content?id=x1uuDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    startDate: "2022-08-20T00:00:00.000Z",
    endDate: "2022-09-15T00:00:00.000Z"
  },
  {
    id: "11",
    title: "Project Hail Mary",
    author: "Andy Weir",
    description: "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish. Except that right now, he doesn't know that. He can't even remember his own name, let alone the nature of his assignment or how to complete it.",
    category: "Science Fiction",
    pages: 496,
    memories: "Stayed up until 3 AM to finish this because I couldn't put it down.",
    comment: "Even better than The Martian. Brilliant sci-fi with heart and humor.",
    rating: 5,
    googleId: "MczYDwAAQBAJ",
    coverImage: "https://books.google.com/books/content?id=MczYDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    startDate: "2024-03-10T00:00:00.000Z",
    endDate: "2024-03-22T00:00:00.000Z"
  },
  {
    id: "12",
    title: "The Alchemist",
    author: "Paulo Coelho",
    description: "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.",
    category: "Fiction",
    pages: 208,
    memories: "Read this during a transition period in my life. The timing felt significant.",
    comment: "A simple story with profound wisdom about following your dreams.",
    rating: 4,
    googleId: "FzVjBgAAQBAJ",
    coverImage: "https://books.google.com/books/content?id=FzVjBgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    startDate: "2023-05-01T00:00:00.000Z",
    endDate: "2023-05-08T00:00:00.000Z"
  }
];

export default mockBooks;